timberwyckfarm_com/apps/articles/urls.py
from django.conf.urls import patterns, url

from timberwyckfarm_com.apps.articles import views
from .feeds import TagFeed, LatestEntries, TagFeedAtom, LatestEntriesAtom

tag_rss = TagFeed()
latest_rss = LatestEntries()
tag_atom = TagFeedAtom()
latest_atom = LatestEntriesAtom()

urlpatterns = patterns('',
    (r'^(?P<year>\d{4})/(?P<month>.{3})/(?P<day>\d{1,2})/(?P<slug>.*)/$', views.redirect_to_article),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/page/(?P<page>\d+)/$', views.display_blog_page, name='articles_in_month_page'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.display_blog_page, name='articles_in_month'),
)

urlpatterns += patterns('',
    url(r'^$', views.display_blog_page, name='articles_archive'),
    url(r'^page/(?P<page>\d+)/$', views.display_blog_page, name='articles_archive_page'),

    url(r'^tag/(?P<tag>.*)/page/(?P<page>\d+)/$', views.display_blog_page, name='articles_display_tag_page'),
    url(r'^tag/(?P<tag>.*)/$', views.display_blog_page, name='articles_display_tag'),

    url(r'^author/(?P<username>.*)/page/(?P<page>\d+)/$', views.display_blog_page, name='articles_by_author_page'),
    url(r'^author/(?P<username>.*)/$', views.display_blog_page, name='articles_by_author'),

    url(r'^(?P<year>\d{4})/(?P<slug>.*)/$', views.display_article, name='articles_display_article'),

    # AJAX
    url(r'^ajax/tag/autocomplete/$', views.ajax_tag_autocomplete, name='articles_tag_autocomplete'),

    # RSS
    url(r'^feeds/latest\.rss$', latest_rss, name='articles_rss_feed_latest'),
    url(r'^feeds/latest/$', latest_rss),
    url(r'^feeds/tag/(?P<slug>[\w_-]+)\.rss$', tag_rss, name='articles_rss_feed_tag'),
    url(r'^feeds/tag/(?P<slug>[\w_-]+)/$', tag_rss),

    # Atom
    url(r'^feeds/atom/latest\.xml$', latest_atom, name='articles_atom_feed_latest'),
    url(r'^feeds/atom/tag/(?P<slug>[\w_-]+)\.xml$', tag_atom, name='articles_atom_feed_tag'),

)

timberwyckfarm_com/apps/notes/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView
from .models import Note, Topic

from .views import NoteList, NoteDetail

urlpatterns = patterns('',
    url(r'^$', NoteList.as_view(), name='notes-index'),
    url('^topics/$', ListView.as_view(model=Topic), name='notes-topic-list'),
    url('^topics/(?P<slug>[+\w]+)/$', DetailView.as_view(model=Topic), name='notes-topic-detail'),
    url(r'^add/$', login_required(CreateView.as_view(model=Note)), name='notes-create'),
    url('^(?P<pk>\d+)/$', NoteDetail.as_view(), name='notes-view'),
    url('^(?P<pk>\d+)/edit/$', login_required(UpdateView.as_view(model=Note)), name='notes-edit'),
)

timberwyckfarm_com/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('timberwyckfarm_com.apps.homepage.urls')),
    (r'^', include('farmyard.urls')),
    (r'^calendar/', include('timberwyckfarm_com.apps.calendarium.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^blog/', include('timberwyckfarm_com.apps.articles.urls')),
    (r'^journal/', include('timberwyckfarm_com.apps.notes.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),
)

urlpatterns += patterns('django.contrib.flatpages.views',
    url(r'^education/$', 'flatpage', {'url': '/education/'},
        name='fl-education'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ) + urlpatterns

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.static import serve
from unipath import FSPath as Path
#from farm.models import Building, Field
from django.views.generic import ListView, DetailView
#from timberwyckfarm_com.sitemap import TWFSitemap

#feeds = {
#   'events': UpcomingEvents,
#   'news': LatestNews,
#}

#sitemaps={
#    'site':TWFSitemap,
#}

if settings.DEBUG:
    urlpatterns = patterns('', 
        (r'^media/(?P<path>.*)$', serve, 
			{'document_root' : Path(__file__).parent.child("media")}),
    )
else:
    urlpatterns = patterns('',)

from django.contrib import admin
admin.autodiscover()

urlpatterns += patterns('',
    #(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    #(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    #url(r'^tour/buildings/$', view=ListView.as_view(model=Building), name="fm-building-list"),
    #url(r'^tour/buildings/(?P<slug>[-\w]+)/$', view=DetailView.as_view(model=Building), name="fm-building-detail"),

    #url(r'^tour/fields/$', view=ListView.as_view(model=Field), name="fm-field-list"),
    #url(r'^tour/fields/(?P<slug>[-\w]+)/$', view=DetailView.as_view(model=Field), name="fm-field-detail"),

    (r'^', include('farm.urls')),
    (r'^events/', include('eventy.urls')),
    (r'^calendar/', include('calendarium.urls')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^photos/', include('photologue.urls')),
    (r'^wiki/', include('wiki.urls')),
    (r'^resources/', include('resources.urls')),
    (r'^notes/', include('notes.urls')),
    #(r'^file-picker/', include(file_picker.site.urls)),
    (r'^', include('articles.urls')),
)
urlpatterns+= patterns('django.contrib.flatpages.views',
    url(r'^tour/$', 'flatpage', {'url': '/tour/'}, name='fl-tour'),
    url(r'^education/$', 'flatpage', {'url': '/education/'}, name='fl-education'),
)

timberwyckfarm_com/apps/calendarium/models.py
"""
Models for the ``calendarium`` app.

The code of these models is highly influenced by or taken from the models of
django-schedule:

https://github.com/thauber/django-schedule/tree/master/schedule/models

"""
import json
from dateutil import rrule

from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.template.defaultfilters import slugify
from django.utils.timezone import timedelta
from django.utils.translation import ugettext_lazy as _

from .constants import FREQUENCY_CHOICES, OCCURRENCE_DECISIONS
from .utils import OccurrenceReplacer
from .widgets import ColorPickerWidget
from filer.fields.image import FilerImageField
from south.modelsinspector import add_introspection_rules


class ColorField(models.CharField):
    """Custom color field to display a color picker."""
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 6
        super(ColorField, self).__init__(*args, **kwargs)
        self.validators.append(RegexValidator(
            regex='^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$',
            message='Only RGB color model inputs allowed, like 00000',
            code='nomatch'))

    def formfield(self, **kwargs):
        kwargs['widget'] = ColorPickerWidget
        return super(ColorField, self).formfield(**kwargs)


add_introspection_rules([], ["^calendarium\.models\.ColorField"])


class EventModelManager(models.Manager):
    """Custom manager for the ``Event`` model class."""
    def get_occurrences(self, start, end, category=None):
        """Returns a list of events and occurrences for the given period."""
        # we always want the time of start and end to be at 00:00
        start = start.replace(minute=0, hour=0)
        end = end.replace(minute=0, hour=0)
        # if we recieve the date of one day as start and end, we need to set
        # end one day forward
        if start == end:
            end = start + timedelta(days=1)

        # retrieving relevant events
        # TODO currently for events with a rule, I can't properly find out when
        # the last occurrence of the event ends, or find a way to filter that,
        # so I'm still fetching **all** events before this period, that have a
        # end_recurring_period.
        # For events without a rule, I fetch only the relevant ones.
        qs = self.get_query_set()
        if category:
            qs = qs.filter(start__lt=end)
            relevant_events = qs.filter(
                Q(category=category) |
                Q(category__parent=category)
            )
        else:
            relevant_events = qs.filter(start__lt=end)
        # get all occurrences for those events that don't already have a
        # persistent match and that lie in this period.
        all_occurrences = []
        for event in relevant_events:
            all_occurrences.extend(event.get_occurrences(start, end))

        # sort and return
        return sorted(all_occurrences, key=lambda x: x.start)


class EventModelMixin(models.Model):
    """
    Abstract base class to prevent code duplication.
    :start: The start date of the event.
    :end: The end date of the event.
    :creation_date: When this event was created.
    :description: The description of the event.

    """
    start = models.DateTimeField(
        verbose_name=_('Start date'),
    )

    end = models.DateTimeField(
        verbose_name=_('End date'),
    )

    creation_date = models.DateTimeField(
        verbose_name=_('Creation date'),
        auto_now_add=True,
    )

    description = models.TextField(
        max_length=2048,
        verbose_name=_('Description'),
        blank=True,
    )

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        # start should override end if end is set wrong. This auto-corrects
        # usage errors when creating or updating events.
        if self.end < self.start:
            self.end = self.start
        return super(EventModelMixin, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class Event(EventModelMixin):
    """
    Hold the information about an event in the calendar.

    :created_by: FK to the ``User``, who created this event.
    :category: FK to the ``EventCategory`` this event belongs to.
    :rule: FK to the definition of the recurrence of an event.
    :end_recurring_period: The possible end of the recurring definition.
    :title: The title of the event.
    :image: Optional image of the event.

    """

    created_by = models.ForeignKey(
        'auth.User',
        verbose_name=_('Created by'),
        related_name='events',
        blank=True, null=True,
    )

    category = models.ForeignKey(
        'EventCategory',
        verbose_name=_('Category'),
        related_name='events',
        null=True, blank=True,
    )

    rule = models.ForeignKey(
        'Rule',
        verbose_name=_('Rule'),
        blank=True, null=True,
    )

    end_recurring_period = models.DateTimeField(
        verbose_name=_('End of recurring'),
        blank=True, null=True,
    )

    title = models.CharField(
        max_length=256,
        verbose_name=_('Title'),
    )

    image = FilerImageField(
        verbose_name=_('Image'),
        related_name='calendarium_event_images',
        null=True, blank=True,
    )

    objects = EventModelManager()

    def get_absolute_url(self):
        return reverse('calendar_event_detail', kwargs={'pk': self.pk})

    def _create_occurrence(self, occ_start, occ_end=None):
        """Creates an Occurrence instance."""
        # if the length is not altered, it is okay to only pass occ_start
        if not occ_end:
            occ_end = occ_start + (self.end - self.start)
        return Occurrence(
            event=self, start=occ_start, end=occ_end,
            # TODO not sure why original start and end also are occ_start/_end
            original_start=occ_start, original_end=occ_end,
            title=self.title, description=self.description,
            creation_date=self.creation_date, created_by=self.created_by)

    def _get_date_gen(self, rr, start, end):
        """Returns a generator to create the start dates for occurrences."""
        date = rr.after(start)
        while end and date <= end or not(end):
            yield date
            date = rr.after(date)

    def _get_occurrence_gen(self, start, end):
        """Computes all occurrences for this event from start to end."""
        # get length of the event
        length = self.end - self.start

        if self.rule:
            # if the end of the recurring period is before the end arg passed
            # the end of the recurring period should be the new end
            if self.end_recurring_period and end and (
                    self.end_recurring_period < end):
                end = self.end_recurring_period
            # making start date generator
            occ_start_gen = self._get_date_gen(
                self.get_rrule_object(),
                start - length, end)

            # chosing the first item from the generator to initiate
            occ_start = occ_start_gen.next()
            while not end or (end and occ_start <= end):
                occ_end = occ_start + length
                yield self._create_occurrence(occ_start, occ_end)
                occ_start = occ_start_gen.next()
        else:
            # check if event is in the period
            if (not end or self.start < end) and self.end >= start:
                yield self._create_occurrence(self.start, self.end)

    def get_occurrences(self, start, end=None):
        """Returns all occurrences from start to end."""
        # get persistent occurrences
        persistent_occurrences = self.occurrences.all()

        # setup occ_replacer with p_occs
        occ_replacer = OccurrenceReplacer(persistent_occurrences)

        # compute own occurrences according to rule that overlap with the
        # period
        occurrence_gen = self._get_occurrence_gen(start, end)
        # get additional occs, that we need to take into concern
        additional_occs = occ_replacer.get_additional_occurrences(
            start, end)
        occ = occurrence_gen.next()
        while not end or (occ.start < end or any(additional_occs)):
            if occ_replacer.has_occurrence(occ):
                p_occ = occ_replacer.get_occurrence(occ)

                # if the persistent occ falls into the period, replace it
                if (end and p_occ.start < end) and p_occ.end >= start:
                    estimated_occ = p_occ
            else:
                # if there is no persistent match, use the original occ
                estimated_occ = occ

            if any(additional_occs) and (
                    estimated_occ.start == additional_occs[0].start):
                final_occ = additional_occs.pop(0)
            else:
                final_occ = estimated_occ
            if not final_occ.cancelled:
                yield final_occ
            occ = occurrence_gen.next()

    def get_parent_category(self):
        """Returns the main category of this event."""
        if self.category.parent:
            return self.category.parent
        return self.category

    def get_rrule_object(self):
        """Returns the rrule object for this ``Event``."""
        if self.rule:
            params = self.rule.get_params()
            frequency = 'rrule.{0}'.format(self.rule.frequency)
            return rrule.rrule(eval(frequency), dtstart=self.start, **params)


class EventCategory(models.Model):
    """
    The category of an event.

    :name: The name of the category.
    :slug: The slug of the category.
    :color: The color of the category.
    :parent: Allows you to create hierarchies of event categories.

    """
    name = models.CharField(

timberwyckfarm_com/apps/notes/forms.py
from django.forms import ModelForm
from notes.models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields=['content', 'markup', 'topic','date', 'public']
        
class BriefNoteForm(ModelForm):
    class Meta:
        model = Note
        fields=['content', 'topic']

timberwyckfarm_com/apps/homepage/views.py
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = 'homepage.html'

timberwyckfarm_com/apps/notes/views.py
from django.views.generic import ListView, DetailView

from .models import Note, Topic

class NoteList(ListView):
    model = Note

    def get_queryset(self):
        if self.request.user.is_authenticated: qs = Note.objects.order_by("-date")
        else: qs = Note.public_objects.order_by("-date")
        return qs

    def get_context_data(self, **kwargs):
        context = super(NoteList, self).get_context_data(**kwargs)
        context['topic_list']=Topic.objects.all()
        return context

class NoteDetail(DetailView):
    model = Note

    def get_queryset(self):
        if self.request.user.is_authenticated: qs = Note.objects.order_by("-date")
        else: qs = Note.public_objects.order_by("-date")
        return qs

timberwyckfarm_com/templates/eventy/_month_table.html
<div class="month_table {{size}}">
  {{month_table|safe}}
</div>

timberwyckfarm_com/templates/eventy/_upcoming_eventtimes.html
    <h3>Upcoming events</h3>
    {% if events %}
    <ul>
    {% for event in events %}
    <li>{{event}} - {{event.start|naturalday}}</li>
    {% endfor %}
    </ul>
	  <p><a href="{% url event-list %}">View our event calendar</a></p>
    {% else %}
    <p>There are no upcoming events right now. Please check back again for updates.</p>
    {% endif %}

timberwyckfarm_com/templates/eventy/_year_table.html
<div class="year_table {{size}}">
  {{year_table|safe}}
</div>

timberwyckfarm_com/templates/eventy/base.html
{% extends "base.html" %}

{% block menu-class %}inv{% endblock %}
{% block extra_headers %}
    <link rel="stylesheet" href="{{MEDIA_URL}}css/calendar.css" type="text/css" media="screen" title="style"  />
{% endblock %}

timberwyckfarm_com/templates/eventy/calendar_list.html
{% extends "eventy/base.html" %}
{% load humanize gencal %}

{% block body %}
<h2>Events</h2>
<h3>Our calendars</h3>
{% for cal in calendar_list %}
<dl>
    <dt><a href="{{cal.get_absolute_url}}">{{cal}}</a></dt>
    <dd>{{cal.description}}</dd>
</dl>
{% endfor %}

{% endblock %}

timberwyckfarm_com/templates/eventy/event_detail.html
{% extends "eventy/base.html" %}
{% load humanize typogrify markup %}

{% block body %}
<div class="grid_12 last">
<h2>{{sermon.title}}</h2>
<h2>Events</h2>
</div>

<div class="grid_8">
    <h3>{{event}}</h3>
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e6c0f350ace61fb"></script>
<!-- AddThis Button END -->
    {{event.description|typogrify|markdown}}
    {% for time in event.upcoming_event_times %}
    <a rel="bookmark" href="{{time.get_absolute_url}}">
        <abbr title="{{time.start|naturalday}}">{{time.start|date:"M"}}</abbr>{{time.start|date:"j"}}<sup>{{time.start|date:"S"}}</sup> <abbr>’{{time.start|date:"y"}}</abbr>
	<sub>{{time.start|date:"f a"}}</sub></a>
    {% endfor %}
</div>

<div class="grid_4 last">

</div>
{% endblock %}

timberwyckfarm_com/templates/eventy/eventtime_archive_month.html
{% extends "eventy/base.html" %}
{% load eventy_tags humanize typogrify markup %}

{% block body %}
<div class="grid_12 last">
    <h2>Events in {{month|date:"F"}} {{month.year}}</h2>
</div>

<div class="grid_12">
    <p class="prev"><a href="{% url ev-events-month year=prev_date.year month=prev_month_str %}" alt="View events from {{prev_date|date:"M"}}">&larr; previous month</a></p>
    <p class="next"><a href="{% url ev-events-month year=next_date.year month=next_month_str %}" alt="View events from {{next_date|date:"M"}}">next month &rarr;</a></p>

    {% show_month event_list month %}
</div>

<div class="grid_4 last">

</div>
{% endblock %}

timberwyckfarm_com/templates/eventy/eventtime_archive_year.html
{% extends "eventy/base.html" %}
{% load humanize typogrify markup eventy_tags %}

{% block body %}
<div class="grid_12 last">
    <h2>Events in {{year}}</h2>
</div>

<div class="grid_8">
    <p class="prev"><a href="{% url ev-events-year year=prev_date.year %}" alt="View events from {{prev_date|date:"Y"}}">&larr; previous year</a></p>
    <p class="next"><a href="{% url ev-events-year year=next_date.year %}" alt="View events from {{next_date|date:"Y"}}">next year&rarr;</a></p>

    {% show_year event_list year %}
</div>

<div class="grid_4 last">

</div>
{% endblock %}

timberwyckfarm_com/templates/eventy/eventtime_detail.html
{% extends "base.html" %}
{% load humanize eventy_tags markup typogrify_tags %}

{% block title %}{{event}} | Event at {% endblock %}

{% block content %}
<div class="grid_8 prefix_2 suffix_2">
<h2>{{event}}</h2>
<h3>{{event.start|naturalday}}</h3>
<h3>{{event.start|date:"f a"}}{% if event.end %} until {{event.end|date:"f a"}}{% endif %}</h3>
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e6c0f350ace61fb"></script>
<!-- AddThis Button END -->
<p>At {{event.place}}</p>

{{event.event.description|markdown|typogrify}}

{{event.notes|markdown|typogrify}}

<p><em>Part of our {{event.event.calendar}} calendar</em></p>

</div>

{% endblock %}

timberwyckfarm_com/templates/eventy/eventtime_list.html
{% extends "eventy/base.html" %}
{% load humanize typogrify_tags markup eventy_tags %}
{% block title %}Events at {% endblock %}

{% block content %}
<div class="grid_8 prefix_2 suffix_2">
<h2>Events</h2>

{% for event in event_list|dictsort:"start" %}
<dl class="vevent">
  <dt>{{event}}</dt>
  <dd class="date">{{event.start|naturalday}}</dd>
  <dd class="time">{{event.start|date:"f a"}}</dd>
  <dd class="detail">{{event.event.description|markdown|typogrify}}</dd>
  <dd class="detail">{{event.notes|markdown|typogrify}}</dd>
  <dd class="alt">{{event.event.calendar}}</dd>
</dl>
{% endfor %}
    <h3>{% now "F Y" %}</h3>
    {% show_month event_list '' 'small' %}
</div>
{% endblock %}